config/routes.rb
Calc::Application.routes.draw do
  resources :pesajes

  resources :clientes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :Actividad, :Email, :Estatura, :FechaNacimiento, :NombreCompleto, :Preferencias, :Sexo, :Telefono
  has_many :pesajes
end

app/models/pesaje.rb
class Pesaje < ActiveRecord::Base
  attr_accessible :ComidasConProteinas, :peso, :cliente_id
  belongs_to :cliente
  validates :cliente_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pesajes_controller.rb
class PesajesController < ApplicationController
  # GET /pesajes
  # GET /pesajes.json
  def index
    @pesajes = Pesaje.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pesajes }
    end
  end

  # GET /pesajes/1
  # GET /pesajes/1.json
  def show
    @pesaje = Pesaje.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pesaje }
    end
  end

  # GET /pesajes/new
  # GET /pesajes/new.json
  def new
    @pesaje = Pesaje.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pesaje }
    end
  end

  # GET /pesajes/1/edit
  def edit
    @pesaje = Pesaje.find(params[:id])
  end

  # POST /pesajes
  # POST /pesajes.json
  def create
    @pesaje = Pesaje.new(params[:pesaje])

    respond_to do |format|
      if @pesaje.save
        format.html { redirect_to @pesaje, notice: 'Pesaje was successfully created.' }
        format.json { render json: @pesaje, status: :created, location: @pesaje }
      else
        format.html { render action: "new" }
        format.json { render json: @pesaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pesajes/1
  # PUT /pesajes/1.json
  def update
    @pesaje = Pesaje.find(params[:id])

    respond_to do |format|
      if @pesaje.update_attributes(params[:pesaje])
        format.html { redirect_to @pesaje, notice: 'Pesaje was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pesaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pesajes/1
  # DELETE /pesajes/1.json
  def destroy
    @pesaje = Pesaje.find(params[:id])
    @pesaje.destroy

    respond_to do |format|
      format.html { redirect_to pesajes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
	base_title = "Calculadora de proteina"
	if page_title.empty?
		base_title
	else
		"#{base_title} | #{page_title}"
	end 
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/pesajes_helper.rb
module PesajesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NombreCompleto %><br />
    <%= f.text_field :NombreCompleto %>
  </div>
  <div class="field">
    <%= f.label :FechaNacimiento %><br />
    <%= f.date_select :FechaNacimiento %>
  </div>
  <div class="field">
    <%= f.label :Sexo %><br />
    <%= f.text_field :Sexo %>
  </div>
  <div class="field">
    <%= f.label :Estatura %><br />
    <%= f.number_field :Estatura %>
  </div>
  <div class="field">
    <%= f.label :Email %><br />
    <%= f.text_field :Email %>
  </div>
  <div class="field">
    <%= f.label :Telefono %><br />
    <%= f.text_field :Telefono %>
  </div>
  <div class="field">
    <%= f.label :Actividad %><br />
    <%= f.text_area :Actividad %>
  </div>
  <div class="field">
    <%= f.label :Preferencias %><br />
    <%= f.text_field :Preferencias %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nombrecompleto</th>
    <th>Fechanacimiento</th>
    <th>Sexo</th>
    <th>Estatura</th>
    <th>Email</th>
    <th>Telefono</th>
    <th>Actividad</th>
    <th>Preferencias</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.NombreCompleto %></td>
    <td><%= cliente.FechaNacimiento %></td>
    <td><%= cliente.Sexo %></td>
    <td><%= cliente.Estatura %></td>
    <td><%= cliente.Email %></td>
    <td><%= cliente.Telefono %></td>
    <td><%= cliente.Actividad %></td>
    <td><%= cliente.Preferencias %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombrecompleto:</b>
  <%= @cliente.NombreCompleto %>
</p>

<p>
  <b>Fechanacimiento:</b>
  <%= @cliente.FechaNacimiento %>
</p>

<p>
  <b>Sexo:</b>
  <%= @cliente.Sexo %>
</p>

<p>
  <b>Estatura:</b>
  <%= @cliente.Estatura %>
</p>

<p>
  <b>Email:</b>
  <%= @cliente.Email %>
</p>

<p>
  <b>Telefono:</b>
  <%= @cliente.Telefono %>
</p>

<p>
  <b>Actividad:</b>
  <%= @cliente.Actividad %>
</p>

<p>
  <b>Preferencias:</b>
  <%= @cliente.Preferencias %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pesajes/_form.html.erb
<%= form_for(@pesaje) do |f| %>
  <% if @pesaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pesaje.errors.count, "error") %> prohibited this pesaje from being saved:</h2>

      <ul>
      <% @pesaje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :peso %><br />
    <%= f.text_field :peso %>
  </div>
  <div class="field">
    <%= f.label :ComidasConProteinas %><br />
    <%= f.number_field :ComidasConProteinas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pesajes/edit.html.erb
<h1>Editing pesaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @pesaje %> |
<%= link_to 'Back', pesajes_path %>

app/views/pesajes/index.html.erb
<h1>Listing pesajes</h1>

<table>
  <tr>
    <th>Peso</th>
    <th>Comidasconproteinas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pesajes.each do |pesaje| %>
  <tr>
    <td><%= pesaje.peso %></td>
    <td><%= pesaje.ComidasConProteinas %></td>
    <td><%= link_to 'Show', pesaje %></td>
    <td><%= link_to 'Edit', edit_pesaje_path(pesaje) %></td>
    <td><%= link_to 'Destroy', pesaje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pesaje', new_pesaje_path %>

app/views/pesajes/new.html.erb
<h1>New pesaje</h1>

<%= render 'form' %>

<%= link_to 'Back', pesajes_path %>

app/views/pesajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Peso:</b>
  <%= @pesaje.peso %>
</p>

<p>
  <b>Comidasconproteinas:</b>
  <%= @pesaje.ComidasConProteinas %>
</p>


<%= link_to 'Edit', edit_pesaje_path(@pesaje) %> |
<%= link_to 'Back', pesajes_path %>